### PR TITLE
Update .clang-format

### PR DESCRIPTION
**Pull request by ghost**
Updates the .clang-format file. This version requires clang-format 10.

**Changes**

```
AlignAfterOpenBracket                       Align -> DontAlign
AllowAllParametersOfDeclarationOnNextLine   true -> false
AllowShortBlocksOnASingleLine               false -> Never
AllowShortFunctionsOnASingleLine            All -> Inline
AlwaysBreakTemplateDeclarations             false -> Yes
BreakBeforeTernaryOperators                 true -> false
BreakConstructorInitializers                BeforeComma -> BeforeColon
ColumnLimit                                 0 -> 80
ConstructorInitializerIndentWidth           2 -> 4
ContinuationIndentWidth                     2 -> 4
IndentCaseLabels                            false -> true
KeepEmptyLinesAtTheStartOfBlocks            true -> false
Standard                                    Cpp11 -> c++17
TabWidth                                    2 -> 4
```

**New**

```
BasedOnStyle                                Google
AlignConsecutiveMacros                      false
AllowAllArgumentsOnNextLine                 false
AllowAllConstructorInitializersOnNextLine   false
AllowShortLambdasOnASingleLine              Empty
BreakInheritanceList                        AfterColon
DeriveLineEnding                            false
IncludeBlocks                               Regroup
IndentGotoLabels                            false
IndentPPDirectives                          AfterHash
SpaceAfterLogicalNot                        false
SpaceBeforeCpp11BracedList                  true
SpaceBeforeCtorInitializerColon             false
SpaceBeforeInheritanceColon                 true
SpaceBeforeRangeBasedForLoopColon           true
SpaceBeforeSquareBrackets                   false
SpaceInEmptyBlock                           false
SpacesInConditionalStatement                false
UseCRLF                                     false
UseTab                                      Never
```

### CODE REVIEW

**Comment by olivier-grech** [comment]
We should probably apply this style on the whole code and include those changes in this MR.

**Comment by ghost** [comment]
How is that?

**Comment by olivier-grech** [comment]
Looks good to me.

**Comment by milkyroute** [comment]
Looks good to me too. However, I noticed some minor problems:
image
This problem is also visible in other similar doxygen comments with other special commands, like here (the `\todo` is misplaced):
image

---

image
Is it possible to keep the initialization of class fields in constructors with one line per field? I think it's clearer.

---

Other than that, it looks good! A little remark though, I'm currently working on something that will change the code quite a lot (I'll greatly lower the importance of the Player class) so I think this PR shouldn't reformat the code, just update the .clang-format. Then the code will be reformatted after I'll have merged my modifications.

**Comment by ghost** [comment]
The .clang-format file is updated and the code deformatted.

The Doxygen issue is fixed.

ss

**Comment by milkyroute** [comment]
Ok thanks! I merge.

**Pull request merged**
