### PR TITLE
Screen Transition Fixes

### PR DESCRIPTION
**Pull request by TelloViz**
I adjust the trigger points of the TPEvent when heading east out of Fauxbourg. #128

### CODE REVIEW

**Review by TelloViz — COMMENTED** [review]
I don't know if you guys are interest in design. But I thought it would be helpful to start a graph of what the event system could look like instead. This is just a start and I admit I don't FULLY grasp all the intricacies what's currently involved. I've followed the code with the debugger and have a slight sense of what's going on. I'm not sure if you'll be able to add to this graph or if I need to set some kind of permission or what? Feel free to ax it or change anything.

**Comment by milkyroute** [comment]
Is the file Events.drawio related to this? Anyway, I don't know how to use it. Could you explain me how it works?

**Comment by TelloViz** [comment]
I didn't mean to add the draw io to the same PR. I'm not certain how it linked it on the repo but I'll look when I'm back at my PC. It's essentially a graph making software online. I like to use it for making class charts and that kinda thing. It links well with Google drive and you can even commit to git from it which is what I did.

Go ahead and delete it from this PR though. It's only related in the sense that it has to do with events involved in doors and screen transitions TPEvents.

**Comment by milkyroute** [comment]
Ok! I've seen the code and it seems fine, so I'll merge right after.

**Review by milkyroute — APPROVED** [review]

**Pull request merged**
