### PR TITLE
QoL & Files For Every OpMon

### PR DESCRIPTION
**Pull request by PyroFlareX**
QoL changes: Added Window resizing, resolving issue #102 

Added a file for each OpMon, mostly a copy & paste, safe to merge if there aren't any other sf::Events used in code.

### CODE REVIEW

**Comment by cyrielcentori** [comment]
Thank you for your contribution, but there is some problems with it.
First, there is a build error, since there is a typing error at "sf::Event::Closed", the last "d" has been forgotten. Also, it doesn't seem to work. I've tested it on linux, and sometimes there is a black egde, the screen is cut, and other weird things like that.
The FPS limit changed to 60 is wrong, because the game is set to have 30 FPS. It simply speeds up the game. And, it may be only a detail, but why creating a custom extension for the OpMon files? I think .json is correct, since it is the format used.
I can try to fix some of this if you don't have time, but I'm quite busy preparing exams for now, so I will probably work on it later.

**Review by milkyroute — CHANGES_REQUESTED** [review]
Thank you for your contribution, but there is some problems with it.
First, there is a build error, since there is a typing error at "sf::Event::Closed", the last "d" has been forgotten. Also, it doesn't seem to work. I've tested it on linux, and sometimes there is a black egde, the screen is cut, and other weird things like that.
The FPS limit changed to 60 is wrong, because the game is set to have 30 FPS. It simply speeds up the game. And, it may be only a detail, but why creating a custom extension for the OpMon files? I think .json is correct, since it is the format used.
I can try to fix some of this if you don't have time, but I'm quite busy preparing exams for now, so I will probably work on it later.

**Comment by PyroFlareX** [comment]
Fixes have been completed. Compiles on my linux system.Window resize not perfect, still needs work. Please merge pull but keep issue open.

**Review by milkyroute — CHANGES_REQUESTED** [review]
It's very likely a git bug, but one of your commits completely rewrote main.cpp to replace the content with the code of Gameloop.hpp. I don't know what happened, but the game doesn't build anymore, of course.
Also, why did you rename the functions in Gameloop? That's not really important but I just wonder.

**Comment by PyroFlareX** [comment]
The reason I renamed it is because of readability.

**Review by milkyroute — APPROVED** [review]

**Comment by milkyroute** [comment]
I merge but in a new branch to maybe fix myself some things, like the screen stretching. If you want to add commits you can make another pull request into this branch.

**Pull request merged**
