### PR TITLE
Cleaned up loose hitboxes on Road 14 east

### PR DESCRIPTION
**Pull request by TelloViz**
#128  Road14EastCleanup

### CODE REVIEW

**Comment by TelloViz** [comment]
69474166-78107a00-0d72-11ea-881d-35fd50cf9db3

**Comment by TelloViz** [comment]
#128

**Comment by TelloViz** [comment]
I still need to fix the Tpevent trigger points for this spot so the issue isn't quite closeable.

**Comment by TelloViz** [comment]
All done, Cyrielle! Can close #128 and merge #130.

**Comment by TelloViz** [comment]
By the way there was an extra TPEvent between road 14 and Euvi that I removed. It was off of the path and seemed like a mistake.

**Review by milkyroute — APPROVED** [review]
Ok, I'm merging!

**Pull request merged**
