### PR TITLE
Changes to how the project is built

### PR DESCRIPTION
**Pull request by ghost**
So, I've been working on rewriting the build system and reorganizing stuff in general.
	* I've flattened the `src` directory. Having all the files in one directory is much easier to navigate in my opinion. Includes get simpler as well. Agree/disagree?
	* Keeping dependencies (like SFML) in the repository (in `/external/`) and having them build with the main project makes dealing with them easier. No need to worry about where to find them or whether they are the correct version, for example. Downside is larger file size (mostly due to `SFML/extlibs`).
	* CMakeLists.txt was almost completely rewritten. I have no experience with Apple platforms, so I'm not sure if anything works there.
	* Required C++20 compiler (gcc/clang/msvc), SFML 2.5.1, and cmake 3.17, yes/no?

I'm sure this needs more work.

### CODE REVIEW

**Review by milkyroute — CHANGES_REQUESTED** [review]
Thanks for the pull request! However, there is some points I would like to discuss before merging.

* Personally, I'm against putting all the files in one folder, but it's an idea I would like to discuss anyway, since I'm not alone programming this game.
* I think it would be better to use git sub-modules to include the external dependencies in the repository without making it way heavier. What are the other dependencies you added aside from the json library and SFML by the way?
* Thanks you for rewriting `CMakeLists.txt`, since I don't know much about how CMake works. (It'll fix #118) Could you make a quick recap on what have changed from the user point of view? (If something has changed)
* C++20 is no longer required since it was causing more problems than it solved (I only wanted to use it for a simple method added to std::map, however some contributors weren't able to make C++20 working so I just recreated the thing myself and came back to C++17) . Ok for SFML and CMake versions though.

**Comment by ghost** [comment]
Alternatively, we could have folders with a very limited number of subfolders, similar to how SFML is organized.

I'll look into using submodules. The extra dependencies I forgot to mention are libraries for formatting ([fmt](https://github.com/fmtlib/fmt)), logging ([spdlog](https://github.com/gabime/spdlog)), and dealing with the TOML format for configuration ([toml++](https://github.com/marzer/tomlplusplus)). fmt is the formatting library that was accepted for C++20.

The extra size from `external` is about 14 MB excluding `SFML/extlibs`, 75.5 including it.

As for CMakeLists.txt:
* The minimum cmake version was increased from 3.3 to 3.17
* Some support for [ccache](https://ccache.dev/) and [clang-tidy](https://clang.llvm.org/extra/clang-tidy/)
* A new `WARNINGS_AS_ERRORS` option
* A ton of warnings have been enabled. Lots of warnings when building the project at the moment.
* [Sanitizer](https://github.com/google/sanitizers) support. `USE_X_SANITIZER` enables sanitizer `X`. For debugging purposes.
* Dependencies are built with the project. This means slower build times but users are not required to already have the correct version of SFML installed  (or any other libraries added in the future). This was more of an experiment. Some other way of managing dependencies (like a package manager) might be preferable.

**Comment by milkyroute** [comment]
Thank you for the recap!

For the limited amount of subfolders, I think it might be good to split the game into the core engine (Currently the "core" folder plus some things I should clean to make it almost independent), the model (In-game objects classes, currently the "model" folder) made dependent only from the "core" folder, and then the different screens that could be seen as "modules" one could easily add or remove (with sometimes dependencies between them, for example the "GameMenu" screen that calls the "OptionsMenu" screen). It would probably need some work to sort things to make them more or less independent, but that could make the addition of new screens easier in the future, and keep the source directory cleaner than just having all the files in it (plus if someone wants to reuse the engine it'll make this easier).
*Edit :* Also for the `utils` folder, I would personally prefer it to be treated as an external dependency. I still have to rename some things to make it completely independent from OpMon, but seen from the includes, it's independent from the game's code.

One last thing, where do you use those new dependencies?

**Comment by ghost** [comment]
Having independent folders is a good idea. I'm not too attached to dumping everything in one directory.

I didn't use those libraries anywhere yet. I wanted to discuss these bigger changes first.

**Comment by milkyroute** [comment]
Ok then! I think it'll be better to put all the files into `src` for now and as soon as your pull request is merged I start working on the new folder structure.

**Comment by olivier-grech** [comment]
I agree with this plan @cyriellecentori.

Also I think what you call `external` is usually called `lib`, @CppSpren.

**Comment by ghost** [comment]
Compressing the larger parts of `extlibs` brings the size of SFML down by about 50 MB, making the total overhead of the `external` directory about 25 MB. Is that acceptable or is a submodule the only option here?

`extlibs` is not needed on linux, and on other platforms, just the libraries that are needed could be decompressed. With a submodule, that extra 50 MB would have to be downloaded just to build.

What are your thoughts?

**Comment by milkyroute** [comment]
Is there a way to make CMake use the dependencies in the path if available, and ask for downloading the submodules only if they are not found? I think it could be a great fallback for people struggling with dependencies on their system.
Else, I don't see why having the external dependencies in the repo would be useful.

**Comment by ghost** [comment]
Yes, that's possible. As long as git is installed.

Keeping the dependencies with the rest of the source just keeps things a bit simpler.
* No need to download anything separately (except for SFML's dependencies on linux).
* Versions are guaranteed to be correct.
* The same flags can be passed when compiling the main project and SFML—debug versions of SFML will be compiled when compiling the main executable in debug mode.
* If we find we need to modify SFML, everything just works.
* The include and lib directories are in known locations, so no need to look for them and no need for `SFML_ROOT`. Everything is self-contained.

On systems where you would need to compile SFML yourself anyway, it just automates the process.

Using submodules when specifically requested could provide some of those benefits. I don't know if I would want to automatically download the dependencies if they are not found. If you simply forget to pass `SFML_ROOT`, you probably don't want to download and compile SFML again.

All of those points apply to non-SFML libraries as well.

I like the idea of just keeping all the source in the main repo. No submodules to complicate things. I'm open to counterarguments though.

**Comment by milkyroute** [comment]
My main counterargument would be the size, since the repo is already quite heavy and since it's a game it will get worse (cloning the repo already takes too much time according to me).
Also dealing with dependencies isn't that much a problem, at least on the most common systems. On Linux, it's really simple, you just have to install it and it just works (with most distributions). On Windows, it's a bit more complicated since you have to put some SFML folders in the path but someone who wants to compile the game must have enough knowledge to manage this. On Mac, I must admit I have no idea on how it works though. 
Also the versions aren't really a problem I think, since we always use the last release. But it could be great to explicit it somewhere.

So as I see it, having the external dependencies in the repo seems more like something that would make the repository heavier without really helping a lot of people (yes, it'll help people that aren't either on windows, linux nor mac, but that doesn't represent a lot of people, and I think someone using another system than these three must have enough knowledge to deal with the dependencies).

And if we use submodules then... I think it's not really useful nor really harmful either (since it'll help a limited number of people but it won't make the repo heavier).

*Edit* : I think the best thing to have is submodules only as a fallback. CMake would search for the dependencies in the path by default, and an option would make it search in the submodules (the user would have to download them first). So if there is a problem with the dependencies, the user can rely on those.

**Comment by olivier-grech** [comment]
On macOs you can use the package manager brew: https://formulae.brew.sh/formula/sfml#default

**Comment by ghost** [comment]
92% of the size comes from `.git/objects/pack/` (350 MB). `git clone --depth 1` on my repo took 10 to 20 seconds for me and the resulting size was about 40 MB total (34%. of that being `.git/objects/pack/`).

For context, a full clone of the main repo takes 5 minutes.

After doing extensive history rewriting, I got the repo down to less than 10 MB. The culprit is old binary files in the history that were deleted. `installers/` `installer/` `resources/` `Resources/` `data/` `exe/` `exeLinux` etc.

**Comment by milkyroute** [comment]
I already tried to rewrite the history in the past but it only worked on the local repository (The old commits stayed on the Github repository and were still downloaded when cloning). I tested to clone your repository and it was incredibly fast, so thank you! However won't it cause problems when merging?

**Comment by ghost** [comment]
Yes, attempting to merge would be problematic at this point.

If you don't care about keeping the history, you could delete the repository and create a new one with the current files as a single commit. Everyone with a fork would need to reclone, then continue as normal. After that point, it would be important to be very careful about pushing large files so we don't end up in this situation again. This is probably the fastest and simplest solution.

I tried it out [here](https://github.com/CppSpren/newop)

The commands I used are

```sh
git clone https://github.com/OpMonTeam/OpMon.git
cd OpMon
rm -rf .git
git init
git add .
git commit -m "Init"
git remote add origin https://github.com/CppSpren/newop.git
git push -u origin master
```

The new repo is about 4 MB.

**Pull request closed without merging**
